name: Verify Azure DevOps Extension Installation
description: Verify that an Azure DevOps extension has been installed correctly
author: Jesse Houwing
branding:
  icon: check-square
  color: green
inputs:
  auth-type:
    description: |-
      Authentication type: 'pat', 'basic', or 'oidc'

      Available for: install, publish, query-version, share, show, unpublish, unshare, wait-for-installation, wait-for-validation.
      Required for: none.
      Default: pat

      - pat: Use Personal Access Token (recommended for most users)
      - basic: Use username/token authentication (for on-premises Azure DevOps Server)
      - oidc: Use Azure OIDC via azure/login action (requires setup, see below)

      PAT Setup:
      Provide a Personal Access Token via the 'token' input

      Basic Auth Setup:
      Provide username and token via 'username' and 'token' inputs

      OIDC Setup:
      Run azure/login action BEFORE this action:

      - uses: azure/login@v2
        with:
          client-id: $``{{ secrets.AZURE_CLIENT_ID }}
          tenant-id: $``{{ secrets.AZURE_TENANT_ID }}
          subscription-id: $``{{ secrets.AZURE_SUBSCRIPTION_ID }}

      Then use auth-type: oidc (no token needed)

      See: https://jessehouwing.net/authenticate-connect-mggraph-using-oidc-in-github-actions/
    required: false
    default: pat
  token:
    description: |-
      Token for marketplace authentication

      Available for: install, publish, query-version, share, show, unpublish, unshare, wait-for-installation, wait-for-validation.
      Required for: none.
      Default: none

      Required when auth-type is 'pat' or 'basic'
      For basic auth, provide the username in `username` and the secret in `token`

      Required scopes: Marketplace (Publish)
      Create a PAT at: https://dev.azure.com/_usersSettings/tokens
    required: false
  username:
    description: |-
      Username for basic authentication

      Available for: install, publish, query-version, share, show, unpublish, unshare, wait-for-installation, wait-for-validation.
      Required for: none.
      Default: none

      Required when auth-type is 'basic'
      Not needed for other auth types

      Use for on-premises TFS or Azure DevOps Server deployments
    required: false
  tfx-version:
    description: |-
      **Version of tfx-cli to use:**

      Available for: install, package, publish, query-version, share, show, unpublish, unshare, wait-for-installation, wait-for-validation.
      Required for: none.
      Default: built-in

      - `built-in` (default): Use tfx-cli bundled with this action
      - `path`: Use tfx-cli from system PATH
      - Version spec: Download specific version from npm (e.g., `^0.17`, `0.17.0`, `latest`)

      **Examples:** `built-in`, `path`, `^0.17`, `latest`
    required: false
    default: built-in
  publisher-id:
    description: |-
      **Publisher ID** that owns the extension.

      Available for: install, package, publish, query-version, share, show, unpublish, unshare, wait-for-installation, wait-for-validation.
      Required for: query-version, show.
      Default: none

      - Must match publisher in manifest (or override it)
      - Required for command: install, query-version, share, show, unpublish, unshare, wait-for-validation.
      - Alphanumeric with hyphens, dots, underscores only

      **Example:** `mycompany` or `my-publisher-id`
    required: false
  extension-id:
    description: |-
      **Extension ID** - unique identifier within the publisher namespace.

      Available for: install, package, publish, query-version, share, show, unpublish, unshare, wait-for-installation, wait-for-validation.
      Required for: query-version, show.
      Default: none

      - Must match ID in manifest (or override it)
      - Combined with Publisher ID forms full identifier: `publisherId.extensionId`
      - Required for command: install, query-version, share, show, unpublish, unshare, wait-for-validation.
      - Alphanumeric with hyphens, dots, underscores only

      **Example:** `my-extension` or `azure-devops-tasks`
    required: false
  accounts:
    description: |-
      **Azure DevOps accounts/organizations** (newline-separated).

      Available for: install, share, unshare, wait-for-installation.
      Required for: install, share, unshare, wait-for-installation.
      Default: none

      - Required for command: install, wait-for-installation, share, unshare.
      - Format: Full organization URL or organization name
      - For install/wait-for-installation: target organizations for installation checks
      - For share/unshare: organizations to grant/remove extension access

      **Example:**
      ```
      https://dev.azure.com/myorg1
      https://dev.azure.com/myorg2
      ```

      Or just:
      ```
      myorg1
      myorg2
      ```
    required: true
  expected-tasks:
    description: |-
      **Expected tasks as JSON** - manually specify tasks to verify.

      Available for: wait-for-installation.
      Required for: none.
      Default: none

      **Format:** Array of objects with `name` and `versions` properties

      **Example:**
      ```json
      [
        {"name": "MyTask", "versions": ["1.0.0", "1.0.1"]},
        {"name": "AnotherTask", "versions": ["2.0.0"]}
      ]
      ```

      **Note:** Use this OR auto-discovery options (manifest-file/vsix-path), not both
    required: false
  manifest-file:
    description: |-
      **Manifest file path(s)** (newline-separated).

      Available for: package, publish, wait-for-installation.
      Required for: none.
      Default: none

      - Defaults to `vss-extension.json` if not specified
      - Can specify multiple manifest files
      - Patterns are relative to the current working directory

      **Example:**
      ```
      vss-extension.json
      manifests/dev/vss-extension.json
      manifests/prod/vss-extension.json
      ```
    required: false
  vsix-path:
    description: |-
      **Path to .vsix file** for auto-extracting task versions.

      Available for: install, share, unpublish, unshare, wait-for-installation, wait-for-validation.
      Required for: none.
      Default: none

      - Extracts task.json files from VSIX package
      - Most convenient when verifying immediately after packaging

      **Note:** Use this OR expected-tasks/manifest-file, not multiple
    required: false
  timeout-minutes:
    description: |-
      **Maximum time to wait** for tasks to become available (in minutes).

      Available for: wait-for-installation.
      Required for: none.
      Default: 10

      - Task polls Azure DevOps at regular intervals
      - If tasks don't appear within timeout, verification fails

      **Default:** `10`
    required: false
    default: '10'
  polling-interval-seconds:
    description: |-
      **Interval between task availability checks** (in seconds).

      Available for: wait-for-installation.
      Required for: none.
      Default: 15

      - How often to check if tasks are available
      - Lower values detect availability faster but create more API calls

      **Recommendation:** 30-60 seconds is usually sufficient

      **Default:** `15`
    required: false
    default: '15'
runs:
  using: composite
  steps:
    - id: wait-for-installation
      uses: jessehouwing/azdo-marketplace@main
      with:
        operation: wait-for-installation
        auth-type: ${{ inputs.auth-type }}
        token: ${{ inputs.token }}
        username: ${{ inputs.username }}
        tfx-version: ${{ inputs.tfx-version }}
        publisher-id: ${{ inputs.publisher-id }}
        extension-id: ${{ inputs.extension-id }}
        accounts: ${{ inputs.accounts }}
        expected-tasks: ${{ inputs.expected-tasks }}
        manifest-file: ${{ inputs.manifest-file }}
        vsix-path: ${{ inputs.vsix-path }}
        timeout-minutes: ${{ inputs.timeout-minutes }}
        polling-interval-seconds: ${{ inputs.polling-interval-seconds }}
