name: 'Azure DevOps Extension Tasks'
description: 'Package, publish, and manage Azure DevOps extensions and Visual Studio Marketplace extensions'
author: 'Jesse Houwing'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  # Operation (required)
  operation:
    description: |
      **Operation to perform:**

      - `package`: Create .vsix package file from manifest
      - `publish`: Publish extension to Visual Studio Marketplace
      - `unpublish`: Remove extension from marketplace
      - `share`: Share private extension with organizations
      - `unshare`: Unshare extension from organizations
      - `install`: Install extension to Azure DevOps organizations
      - `show`: Query and display extension metadata
      - `query-version`: Query latest extension version and optionally increment it
      - `wait-for-validation`: Wait for extension validation to complete
      - `wait-for-installation`: Wait for tasks to be available after installation
    required: true

  # Authentication
  auth-type:
    description: |
      Authentication type: 'pat', 'basic', or 'oidc'
      - pat: Use Personal Access Token (recommended for most users)
      - basic: Use username/password authentication (for on-premises Azure DevOps Server)
      - oidc: Use Azure OIDC via azure/login action (requires setup, see below)

      PAT Setup:
      Provide a Personal Access Token via the 'token' input

      Basic Auth Setup:
      Provide username and password via 'username' and 'password' inputs

      OIDC Setup:
      Run azure/login action BEFORE this action:

      - uses: azure/login@v2
        with:
          client-id: $``{{ secrets.AZURE_CLIENT_ID }}
          tenant-id: $``{{ secrets.AZURE_TENANT_ID }}
          subscription-id: $``{{ secrets.AZURE_SUBSCRIPTION_ID }}

      Then use auth-type: oidc (no token needed)

      See: https://jessehouwing.net/authenticate-connect-mggraph-using-oidc-in-github-actions/

      Default: pat
    required: false
    default: 'pat'
  token:
    description: |
      Personal Access Token for marketplace authentication
      Required when auth-type is 'pat'
      Not needed for other auth types

      Required scopes: Marketplace (Publish)
      Create a PAT at: https://dev.azure.com/_usersSettings/tokens
    required: false
  username:
    description: |
      Username for basic authentication
      Required when auth-type is 'basic'
      Not needed for other auth types

      Use for on-premises TFS or Azure DevOps Server deployments
    required: false
  password:
    description: |
      Password for basic authentication
      Required when auth-type is 'basic'
      Not needed for other auth types

      Use for on-premises TFS or Azure DevOps Server deployments
    required: false
  service-url:
    description: |
      Azure DevOps service URL (optional)

      - Defaults to marketplace URL for cloud operations
      - For `wait-for-installation`, this is required and must point to an Azure DevOps organization/server endpoint
      - Recommended cloud format: `https://dev.azure.com/<organization>`
      - Azure DevOps Server/TFS URLs are also supported
      - Specify custom URL for on-premises Azure DevOps Server
      - Must be HTTPS and valid Azure DevOps domain

      Examples:
      - https://marketplace.visualstudio.com (default)
      - https://dev.azure.com/myorg
      - https://myserver.com/Collection
      - https://myserver.com/tfs/Collection
    required: false

  # TFX Configuration
  tfx-version:
    description: |
      **Version of tfx-cli to use:**

      - `built-in` (default): Use tfx-cli bundled with this action
      - `path`: Use tfx-cli from system PATH
      - Version spec: Download specific version from npm (e.g., `^0.17`, `0.17.0`, `latest`)

      **Examples:** `built-in`, `path`, `^0.17`, `latest`
    required: false
    default: 'built-in'

  # Extension Identity
  publisher-id:
    description: |
      **Publisher ID** that owns the extension.

      - Must match publisher in manifest (or override it)
      - Required for command: install, query-version, share, show, unpublish, unshare, wait-for-installation, wait-for-validation.
      - Alphanumeric with hyphens, dots, underscores only

      **Example:** `mycompany` or `my-publisher-id`
    required: false
  extension-id:
    description: |
      **Extension ID** - unique identifier within the publisher namespace.

      - Must match ID in manifest (or override it)
      - Combined with Publisher ID forms full identifier: `publisherId.extensionId`
      - Required for command: install, query-version, share, show, unpublish, unshare, wait-for-installation, wait-for-validation.
      - Alphanumeric with hyphens, dots, underscores only

      **Example:** `my-extension` or `azure-devops-tasks`
    required: false

  # Package & Publish - Manifest Source
  root-folder:
    description: |
      **Root folder** containing extension manifest and source files.

      - Defaults to repository root if not specified
      - All file paths in manifest are relative to this folder
      - Must contain `vss-extension.json` (or other manifest specified in manifest-globs)
    required: false
  manifest-globs:
    description: |
      **Glob patterns for manifest files** (newline-separated).

      - Defaults to `vss-extension.json` if not specified
      - Can specify multiple patterns for multi-manifest scenarios
      - Patterns are relative to root-folder

      **Example:**
      ```
      vss-extension.json
      manifests/**/*.json
      ```
    required: false

  # Package & Publish - VSIX Source
  vsix-file:
    description: |
      **Path to pre-built .vsix file** (for publish operation).

      - Use when publish-source is 'vsix'
      - File must be a valid extension package
      - Supports GitHub Actions expressions

      **Example:** `$``{{ github.workspace }}/dist/my-extension.vsix`
    required: false
  publish-source:
    description: |
      **Source for publish operation:**

      - `manifest` (default): Build extension from manifest and source files
      - `vsix`: Publish a pre-built .vsix package

      **Use VSIX when:** You've already packaged the extension separately
    required: false
    default: 'manifest'

  # Extension Metadata Overrides
  extension-version:
    description: |
      **Override extension version** specified in manifest.

      - Must follow semantic versioning: `major.minor.patch`
      - Useful for CI/CD pipelines to inject build numbers

      **Examples:** `1.2.3`, `1.0.$``{{ github.run_number }}`
    required: false
  extension-name:
    description: |
      **Override extension display name** shown in marketplace.

      - Does not affect the extension ID
      - Useful for creating branded variants (e.g., "My Extension (Dev)")

      **Example:** `My Extension - Development`
    required: false
  extension-visibility:
    description: |
      **Override extension visibility** in marketplace.

      - `private`: Only visible to organizations you share it with
      - `public`: Visible to everyone in the marketplace
      - `private_preview`: Private extension in preview mode
      - `public_preview`: Public extension in preview mode

      **Note:** Private extensions must be explicitly shared with organizations
    required: false

  # Package Options
  output-path:
    description: |
      **Output directory** for generated .vsix file (package operation).

      - Defaults to current directory if not specified
      - Directory will be created if it doesn't exist
      - Actual filename is based on publisher.extensionId-version.vsix

      **Output:** Full path stored in `vsix-path` output
    required: false
  output-variable:
    description: |
      **Name to use for storing output** (deprecated - use outputs instead).

      **Package:** Stores path to generated .vsix file
      **Show:** Stores JSON metadata about the extension

      **Note:** Prefer using action outputs (`steps.<id>.outputs.vsix-path`)
    required: false
  bypass-validation:
    description: |
      **Skip extension validation checks** during package/publish.

      - Not recommended for production use
      - Use only when validation incorrectly fails
      - May result in extension rejection by marketplace

      **Default:** `false` (validation enabled)
    required: false
    default: 'false'
  rev-version:
    description: |
      **Automatically increment the patch version** of the extension.

      - Increments the last digit: `1.2.3` → `1.2.4`
      - Applied before packaging
      - Does not modify source manifest file

      **Default:** `false`
    required: false
    default: 'false'

  # Publish Options
  share-with:
    description: |
      **Organizations to share extension with** (newline-separated).

      - Required for command: share.
      - Format: organization name only (not full URL)

      **Example:**
      ```
      myorg1
      myorg2
      contoso
      ```
    required: false
  no-wait-validation:
    description: |
      **Do not wait for marketplace validation** after publishing.

      - By default, action waits for validation (can take several minutes)
      - Enable to publish and continue immediately
      - Extension may not be immediately available

      **Default:** `false` (waits for validation)
    required: false
    default: 'false'
  update-tasks-version:
    description: |
      **Automatically update task versions** to match extension version.

      - Updates all task.json files in the extension
      - Useful for keeping task and extension versions in sync

      **Default:** `false`
    required: false
    default: 'false'
  update-tasks-id:
    description: |
      **Generate new deterministic task IDs** for all tasks.

      - Creates UUID v5 IDs based on publisher + extension + task name
      - Use when creating extension variants (dev, test versions)

      **Warning:** Changing task IDs creates new tasks - existing pipelines won't auto-update

      **Default:** `false`
    required: false
    default: 'false'

  # Share/Unshare Options
  unshare-with:
    description: |
      **Organizations to unshare extension from** (newline-separated).

      - Required for command: unshare.
      - Removes extension access from specified organizations
      - Format: organization name only (not full URL)

      **Example:**
      ```
      oldorg1
      oldorg2
      ```
    required: false

  # Install Options
  accounts:
    description: |
      **Azure DevOps accounts/organizations** to install extension to (newline-separated).

      - Required for command: install, wait-for-installation.
      - Format: Full organization URL or organization name
      - Organizations must have access to the extension (shared if private)
      - Requires organization administrator permissions

      **Example:**
      ```
      https://dev.azure.com/myorg1
      https://dev.azure.com/myorg2
      ```

      Or just:
      ```
      myorg1
      myorg2
      ```
    required: false

  # WaitForValidation Options
  max-retries:
    description: |
      **Maximum retry attempts** for extension validation.

      - Validation can take time as marketplace processes the extension
      - Task retries with exponential backoff

      **Default:** `10`
    required: false
    default: '10'
  min-timeout:
    description: |
      **Minimum timeout between retry attempts** (in minutes).

      - Initial wait time before first retry
      - Increases exponentially up to max-timeout

      **Default:** `1`
    required: false
    default: '1'
  max-timeout:
    description: |
      **Maximum timeout between retry attempts** (in minutes).

      - Maximum wait time between retries
      - Timeout increases exponentially from min-timeout

      **Default:** `15`
    required: false
    default: '15'

  # QueryVersion Options
  version-action:
    description: |
      **Action to apply to the marketplace version**.

      - `None`: Use the current latest marketplace version
      - `Major`: Increment major and reset minor/patch
      - `Minor`: Increment minor and reset patch
      - `Patch`: Increment patch

      **Example:** If latest is `1.2.3` and action is `Minor`, result is `1.3.0`
    required: false
    default: 'None'
  extension-version-override:
    description: |
      **Variable name containing a version override**.

      If set and the variable exists, that value is used instead of querying marketplace.

      **Example:** `MY_VERSION` where `$``{{ env.MY_VERSION }}` is `2.1.0`
    required: false

  # WaitForInstallation Options
  expected-tasks:
    description: |
      **Expected tasks as JSON** - manually specify tasks to verify.

      **Format:** Array of objects with `name` and `versions` properties

      **Example:**
      ```json
      [
        {"name": "MyTask", "versions": ["1.0.0", "1.0.1"]},
        {"name": "AnotherTask", "versions": ["2.0.0"]}
      ]
      ```

      **Note:** Use this OR auto-discovery options (manifest-path/vsix-path), not both
    required: false
  manifest-path:
    description: |
      **Path to extension manifest** for auto-discovering task versions.

      - Reads manifest to find all tasks and their versions
      - More convenient than manually specifying expected tasks

      **Note:** Use this OR expected-tasks/vsix-path, not multiple
    required: false
  vsix-path:
    description: |
      **Path to .vsix file** for auto-extracting task versions.

      - Extracts task.json files from VSIX package
      - Most convenient when verifying immediately after packaging

      **Note:** Use this OR expected-tasks/manifest-path, not multiple
    required: false
  timeout-minutes:
    description: |
      **Maximum time to wait** for tasks to become available (in minutes).

      - Task polls Azure DevOps at regular intervals
      - If tasks don't appear within timeout, verification fails

      **Default:** `10`
    required: false
    default: '10'
  polling-interval-seconds:
    description: |
      **Interval between task availability checks** (in seconds).

      - How often to check if tasks are available
      - Lower values detect availability faster but create more API calls

      **Recommendation:** 30-60 seconds is usually sufficient

      **Default:** `30`
    required: false
    default: '30'

outputs:
  vsix-path:
    description: |
      **Path to generated .vsix file** (package operation only).

      **Example usage:**
      ```yaml
      - uses: jessehouwing/azure-devops-extension-tasks@refactor/v6
        id: package
        with:
          operation: package

      - run: echo "VSIX at $``{{ steps.package.outputs.vsix-path }}"
      ```
  extension-metadata:
    description: |
      **Extension metadata as JSON** (show operation only).

      Contains complete extension information from marketplace including:
      - Publisher and extension IDs
      - Version information
      - Statistics (downloads, ratings)
      - Categories and tags

      **Example usage:**
      ```yaml
      - uses: jessehouwing/azure-devops-extension-tasks@refactor/v6
        id: show
        with:
          operation: show
          publisher-id: mycompany
          extension-id: my-extension

      - run: echo '$``{{ steps.show.outputs.extension-metadata }}' | jq .
      ```
  proposed-version:
    description: |
      **Proposed extension version** after applying version action (query-version operation only).
  current-version:
    description: |
      **Current marketplace version** before applying version action (query-version operation only).

runs:
  using: 'node24'
  main: 'packages/github-action/dist/bundle.js'
