name: Azure DevOps Extension Tasks
description: Package, publish, and manage Azure DevOps extensions and Visual Studio Marketplace extensions
author: Jesse Houwing
branding:
  icon: package
  color: blue
inputs:
  operation:
    description: |-
      **Operation to perform:**

      Available for: install, package, publish, query-version, share, show, unpublish, unshare, wait-for-installation, wait-for-validation.
      Required for: install, package, publish, query-version, share, show, unpublish, unshare, wait-for-installation, wait-for-validation.
      Default: none

      - `package`: Create .vsix package file from manifest
      - `publish`: Publish extension to Visual Studio Marketplace
      - `unpublish`: Remove extension from marketplace
      - `share`: Share private extension with organizations
      - `unshare`: Unshare extension from organizations
      - `install`: Install extension to Azure DevOps organizations
      - `show`: Query and display extension metadata
      - `query-version`: Query latest extension version and optionally increment it
      - `wait-for-validation`: Wait for extension validation to complete
      - `wait-for-installation`: Wait for tasks to be available after installation
    required: true
  auth-type:
    description: |-
      Authentication type: 'pat', 'basic', or 'oidc'

      Available for: install, publish, query-version, share, show, unpublish, unshare, wait-for-installation, wait-for-validation.
      Required for: none.
      Default: pat

      - pat: Use Personal Access Token (recommended for most users)
      - basic: Use username/token authentication (for on-premises Azure DevOps Server)
      - oidc: Use Azure OIDC via azure/login action (requires setup, see below)

      PAT Setup:
      Provide a Personal Access Token via the 'token' input

      Basic Auth Setup:
      Provide username and token via 'username' and 'token' inputs

      OIDC Setup:
      Run azure/login action BEFORE this action:

      - uses: azure/login@v2
        with:
          client-id: $``{{ secrets.AZURE_CLIENT_ID }}
          tenant-id: $``{{ secrets.AZURE_TENANT_ID }}
          subscription-id: $``{{ secrets.AZURE_SUBSCRIPTION_ID }}

      Then use auth-type: oidc (no token needed)

      See: https://jessehouwing.net/authenticate-connect-mggraph-using-oidc-in-github-actions/
    required: false
    default: pat
  token:
    description: |-
      Token for marketplace authentication

      Available for: install, publish, query-version, share, show, unpublish, unshare, wait-for-installation, wait-for-validation.
      Required for: none.
      Default: none

      Required when auth-type is 'pat' or 'basic'
      For basic auth, provide the username in `username` and the secret in `token`

      Required scopes: Marketplace (Publish)
      Create a PAT at: https://dev.azure.com/_usersSettings/tokens
    required: false
  username:
    description: |-
      Username for basic authentication

      Available for: install, publish, query-version, share, show, unpublish, unshare, wait-for-installation, wait-for-validation.
      Required for: none.
      Default: none

      Required when auth-type is 'basic'
      Not needed for other auth types

      Use for on-premises TFS or Azure DevOps Server deployments
    required: false
  service-url:
    description: |-
      Azure DevOps service URL (optional)

      Available for: publish, query-version, share, show, unpublish, unshare, wait-for-validation.
      Required for: none.
      Default: none

      - Defaults to marketplace URL for cloud operations
      - Recommended cloud format: `https://dev.azure.com/<organization>`
      - Azure DevOps Server/TFS URLs are also supported
      - Specify custom URL for on-premises Azure DevOps Server
      - Must be HTTPS and valid Azure DevOps domain

      Examples:
      - https://marketplace.visualstudio.com (default)
      - https://dev.azure.com/myorg
      - https://myserver.com/Collection
      - https://myserver.com/tfs/Collection

      Optional for: publish, share, unshare, show, query-version, wait-for-validation
    required: false
  tfx-version:
    description: |-
      **Version of tfx-cli to use:**

      Available for: install, package, publish, query-version, share, show, unpublish, unshare, wait-for-installation, wait-for-validation.
      Required for: none.
      Default: built-in

      - `built-in` (default): Use tfx-cli bundled with this action
      - `path`: Use tfx-cli from system PATH
      - Version spec: Download specific version from npm (e.g., `^0.17`, `0.17.0`, `latest`)

      **Examples:** `built-in`, `path`, `^0.17`, `latest`
    required: false
    default: built-in
  publisher-id:
    description: |-
      **Publisher ID** that owns the extension.

      Available for: install, package, publish, query-version, share, show, unpublish, unshare, wait-for-installation, wait-for-validation.
      Required for: query-version, show.
      Default: none

      - Must match publisher in manifest (or override it)
      - Required for command: install, query-version, share, show, unpublish, unshare, wait-for-validation.
      - Alphanumeric with hyphens, dots, underscores only

      **Example:** `mycompany` or `my-publisher-id`
    required: false
  extension-id:
    description: |-
      **Extension ID** - unique identifier within the publisher namespace.

      Available for: install, package, publish, query-version, share, show, unpublish, unshare, wait-for-installation, wait-for-validation.
      Required for: query-version, show.
      Default: none

      - Must match ID in manifest (or override it)
      - Combined with Publisher ID forms full identifier: `publisherId.extensionId`
      - Required for command: install, query-version, share, show, unpublish, unshare, wait-for-validation.
      - Alphanumeric with hyphens, dots, underscores only

      **Example:** `my-extension` or `azure-devops-tasks`
    required: false
  manifest-file:
    description: |-
      **Manifest file path(s)** (newline-separated).

      Available for: package, publish, wait-for-installation.
      Required for: none.
      Default: none

      - Defaults to `vss-extension.json` if not specified
      - Can specify multiple manifest files
      - Patterns are relative to the current working directory

      **Example:**
      ```
      vss-extension.json
      manifests/dev/vss-extension.json
      manifests/prod/vss-extension.json
      ```
    required: false
  manifest-file-js:
    description: |-
      **Manifest JS file path** for tfx `--manifest-js`.

      Available for: package, publish.
      Required for: none.
      Default: none

      - Path to JavaScript file exporting a function that returns manifest JSON
      - Path is relative to the current working directory
      - Optional alternative/addition to `manifest-file`
    required: false
  overrides-file:
    description: |-
      **Overrides JSON file path** for tfx `--overrides-file`.

      Available for: package, publish.
      Required for: none.
      Default: none

      - Existing JSON is preserved unless overridden by explicit inputs
      - Manifest updates from this action are merged into this file
      - Path is relative to the current working directory
    required: false
  vsix-file:
    description: |-
      **Path to pre-built .vsix file** (for publish operation).

      Available for: publish.
      Required for: none.
      Default: none

      - Use when publish-source is 'vsix'
      - File must be a valid extension package
      - Supports GitHub Actions expressions

      **Example:** `$``{{ github.workspace }}/dist/my-extension.vsix`
    required: false
  publish-source:
    description: |-
      **Source for publish operation:**

      Available for: publish.
      Required for: none.
      Default: manifest

      - `manifest` (default): Build extension from manifest and source files
      - `vsix`: Publish a pre-built .vsix package

      **Use VSIX when:** You've already packaged the extension separately
    required: false
    default: manifest
  extension-version:
    description: |-
      **Override extension version** specified in manifest.

      Available for: package, publish, wait-for-validation.
      Required for: none.
      Default: none

      - Must follow semantic versioning: `major.minor.patch`
      - Useful for CI/CD pipelines to inject build numbers

      **Examples:** `1.2.3`, `1.0.$``{{ github.run_number }}`
    required: false
  extension-name:
    description: |-
      **Override extension display name** shown in marketplace.

      Available for: package, publish.
      Required for: none.
      Default: none

      - Does not affect the extension ID
      - Useful for creating branded variants (e.g., "My Extension (Dev)")

      **Example:** `My Extension - Development`
    required: false
  extension-visibility:
    description: |-
      **Override extension visibility** in marketplace.

      Available for: package, publish.
      Required for: none.
      Default: none

      - `private`: Only visible to organizations you share it with
      - `public`: Visible to everyone in the marketplace
      - `private_preview`: Private extension in preview mode
      - `public_preview`: Public extension in preview mode

      **Note:** Private extensions must be explicitly shared with organizations
    required: false
  localization-root:
    description: |-
      **Folder containing localization files** for multi-language support.

      Available for: package, publish.
      Required for: none.
      Default: none

      - Should contain language-specific resource files
      - Typical structure: `localization/{locale}/resources.resjson`
      - If not specified, no localization is included

      **Example:** `$``{{ github.workspace }}/localization`
    required: false
  extension-pricing:
    description: |-
      **Override extension pricing model**.

      Available for: package, publish.
      Required for: none.
      Default: default

      - `default`: Use pricing from manifest
      - `free`: Extension is free to use
      - `paid`: Extension requires payment

      **Note:** Paid extensions require additional marketplace publisher verification
    required: false
    default: default
  output-path:
    description: |-
      **Output directory** for generated/final .vsix file.

      Available for: package, publish.
      Required for: none.
      Default: none

      - Defaults to current directory if not specified
      - Directory will be created if it doesn't exist
      - Actual filename is based on publisher.extensionId-version.vsix

      **Output:** Full path stored in `vsix-path` output
    required: false
  bypass-validation:
    description: |-
      **Skip extension validation checks** during package/publish.

      Available for: package.
      Required for: none.
      Default: false

      - Not recommended for production use
      - Use only when validation incorrectly fails
      - May result in extension rejection by marketplace

      **Default:** `false` (validation enabled)
    required: false
    default: 'false'
  no-wait-validation:
    description: |-
      **Do not wait for marketplace validation** after publishing.

      Available for: publish.
      Required for: none.
      Default: false

      - By default, action waits for validation (can take several minutes)
      - Enable to publish and continue immediately
      - Extension may not be immediately available

      **Default:** `false` (waits for validation)
    required: false
    default: 'false'
  update-tasks-version:
    description: |-
      **How to update task versions** to match extension version.

      Available for: package, publish.
      Required for: none.
      Default: none

      - `none`: Do not update task versions
      - `major`: Replace major, minor, patch
      - `minor`: Replace minor, patch
      - `patch`: Replace patch only

      **Default:** `none`
    required: false
    default: none
  update-tasks-id:
    description: |-
      **Generate new deterministic task IDs** for all tasks.

      Available for: package, publish.
      Required for: none.
      Default: false

      - Creates UUID v5 IDs based on publisher + extension + task name
      - Use when creating extension variants (dev, test versions)

      **Warning:** Changing task IDs creates new tasks - existing pipelines won't auto-update

      **Default:** `false`
    required: false
    default: 'false'
  accounts:
    description: |-
      **Azure DevOps accounts/organizations** (newline-separated).

      Available for: install, share, unshare, wait-for-installation.
      Required for: install, share, unshare, wait-for-installation.
      Default: none

      - Required for command: install, wait-for-installation, share, unshare.
      - Format: Full organization URL or organization name
      - For install/wait-for-installation: target organizations for installation checks
      - For share/unshare: organizations to grant/remove extension access

      **Example:**
      ```
      https://dev.azure.com/myorg1
      https://dev.azure.com/myorg2
      ```

      Or just:
      ```
      myorg1
      myorg2
      ```
    required: false
  max-retries:
    description: |-
      **Maximum retry attempts** for extension validation.

      Available for: wait-for-validation.
      Required for: none.
      Default: 10

      - Validation can take time as marketplace processes the extension
      - Task retries with exponential backoff

      **Default:** `10`
    required: false
    default: '10'
  min-timeout:
    description: |-
      **Minimum timeout between retry attempts** (in minutes).

      Available for: wait-for-validation.
      Required for: none.
      Default: 1

      - Initial wait time before first retry
      - Increases exponentially up to max-timeout

      **Default:** `1`
    required: false
    default: '1'
  max-timeout:
    description: |-
      **Maximum timeout between retry attempts** (in minutes).

      Available for: wait-for-validation.
      Required for: none.
      Default: 15

      - Maximum wait time between retries
      - Timeout increases exponentially from min-timeout

      **Default:** `15`
    required: false
    default: '15'
  version-action:
    description: |-
      **Action to apply to the marketplace version**.

      Available for: query-version.
      Required for: none.
      Default: None

      - `None`: Use the current latest marketplace version
      - `Major`: Increment major and reset minor/patch
      - `Minor`: Increment minor and reset patch
      - `Patch`: Increment patch

      **Example:** If latest is `1.2.3` and action is `Minor`, result is `1.3.0`
    required: false
    default: None
  extension-version-override:
    description: |-
      **Variable name containing a version override**.

      Available for: query-version.
      Required for: none.
      Default: none

      If set and the variable exists, that value is used instead of querying marketplace.

      **Example:** `MY_VERSION` where `$``{{ env.MY_VERSION }}` is `2.1.0`
    required: false
  expected-tasks:
    description: |-
      **Expected tasks as JSON** - manually specify tasks to verify.

      Available for: wait-for-installation.
      Required for: none.
      Default: none

      **Format:** Array of objects with `name` and `versions` properties

      **Example:**
      ```json
      [
        {"name": "MyTask", "versions": ["1.0.0", "1.0.1"]},
        {"name": "AnotherTask", "versions": ["2.0.0"]}
      ]
      ```

      **Note:** Use this OR auto-discovery options (manifest-file/vsix-path), not both
    required: false
  vsix-path:
    description: |-
      **Path to .vsix file** for auto-extracting task versions.

      Available for: install, share, unpublish, unshare, wait-for-installation, wait-for-validation.
      Required for: none.
      Default: none

      - Extracts task.json files from VSIX package
      - Most convenient when verifying immediately after packaging

      **Note:** Use this OR expected-tasks/manifest-file, not multiple
    required: false
  timeout-minutes:
    description: |-
      **Maximum time to wait** for tasks to become available (in minutes).

      Available for: wait-for-installation.
      Required for: none.
      Default: 10

      - Task polls Azure DevOps at regular intervals
      - If tasks don't appear within timeout, verification fails

      **Default:** `10`
    required: false
    default: '10'
  polling-interval-seconds:
    description: |-
      **Interval between task availability checks** (in seconds).

      Available for: wait-for-installation.
      Required for: none.
      Default: 15

      - How often to check if tasks are available
      - Lower values detect availability faster but create more API calls

      **Recommendation:** 30-60 seconds is usually sufficient

      **Default:** `15`
    required: false
    default: '15'
outputs:
  vsix-path:
    description: |
      **Path to generated .vsix file** (package operation only).

      **Example usage:**
      ```yaml
      - uses: jessehouwing/azdo-marketplace@v6
        id: package
        with:
          operation: package

      - run: echo "VSIX at $``{{ steps.package.outputs.vsix-path }}"
      ```
  extension-metadata:
    description: |
      **Extension metadata as JSON** (show operation only).

      Contains complete extension information from marketplace including:
      - Publisher and extension IDs
      - Version information
      - Statistics (downloads, ratings)
      - Categories and tags

      **Example usage:**
      ```yaml
      - uses: jessehouwing/azdo-marketplace@v6
        id: show
        with:
          operation: show
          publisher-id: mycompany
          extension-id: my-extension

      - run: echo '$``{{ steps.show.outputs.extension-metadata }}' | jq .
      ```
  proposed-version:
    description: |
      **Proposed extension version** after applying version action (query-version operation only).
  current-version:
    description: |
      **Current marketplace version** before applying version action (query-version operation only).
runs:
  using: node24
  main: packages/github-action/dist/bundle.js
