name: Query Azure DevOps Extension Version
description: Query extension version from marketplace with optional version increment logic
author: Jesse Houwing
branding:
  icon: search
  color: blue
inputs:
  auth-type:
    description: |-
      Authentication type: 'pat', 'basic', or 'oidc'

      Available for: install, publish, query-version, share, show, unpublish, unshare, wait-for-installation, wait-for-validation.
      Required for: none.
      Default: pat

      - pat: Use Personal Access Token (recommended for most users)
      - basic: Use username/token authentication (for on-premises Azure DevOps Server)
      - oidc: Use Azure OIDC via azure/login action (requires setup, see below)

      PAT Setup:
      Provide a Personal Access Token via the 'token' input

      Basic Auth Setup:
      Provide username and token via 'username' and 'token' inputs

      OIDC Setup:
      Run azure/login action BEFORE this action:

      - uses: azure/login@v2
        with:
          client-id: $``{{ secrets.AZURE_CLIENT_ID }}
          tenant-id: $``{{ secrets.AZURE_TENANT_ID }}
          subscription-id: $``{{ secrets.AZURE_SUBSCRIPTION_ID }}

      Then use auth-type: oidc (no token needed)

      See: https://jessehouwing.net/authenticate-connect-mggraph-using-oidc-in-github-actions/
    required: false
    default: pat
  token:
    description: |-
      Token for marketplace authentication

      Available for: install, publish, query-version, share, show, unpublish, unshare, wait-for-installation, wait-for-validation.
      Required for: none.
      Default: none

      Required when auth-type is 'pat' or 'basic'
      For basic auth, provide the username in `username` and the secret in `token`

      Required scopes: Marketplace (Publish)
      Create a PAT at: https://dev.azure.com/_usersSettings/tokens
    required: false
  username:
    description: |-
      Username for basic authentication

      Available for: install, publish, query-version, share, show, unpublish, unshare, wait-for-installation, wait-for-validation.
      Required for: none.
      Default: none

      Required when auth-type is 'basic'
      Not needed for other auth types

      Use for on-premises TFS or Azure DevOps Server deployments
    required: false
  service-url:
    description: |-
      Azure DevOps service URL (optional)

      Available for: publish, query-version, share, show, unpublish, unshare, wait-for-validation.
      Required for: none.
      Default: none

      - Defaults to marketplace URL for cloud operations
      - Recommended cloud format: `https://dev.azure.com/<organization>`
      - Azure DevOps Server/TFS URLs are also supported
      - Specify custom URL for on-premises Azure DevOps Server
      - Must be HTTPS and valid Azure DevOps domain

      Examples:
      - https://marketplace.visualstudio.com (default)
      - https://dev.azure.com/myorg
      - https://myserver.com/Collection
      - https://myserver.com/tfs/Collection

      Optional for: publish, share, unshare, show, query-version, wait-for-validation
    required: false
  tfx-version:
    description: |-
      **Version of tfx-cli to use:**

      Available for: install, package, publish, query-version, share, show, unpublish, unshare, wait-for-installation, wait-for-validation.
      Required for: none.
      Default: built-in

      - `built-in` (default): Use tfx-cli bundled with this action
      - `path`: Use tfx-cli from system PATH
      - Version spec: Download specific version from npm (e.g., `^0.17`, `0.17.0`, `latest`)

      **Examples:** `built-in`, `path`, `^0.17`, `latest`
    required: false
    default: built-in
  publisher-id:
    description: |-
      **Publisher ID** that owns the extension.

      Available for: install, package, publish, query-version, share, show, unpublish, unshare, wait-for-installation, wait-for-validation.
      Required for: query-version, show.
      Default: none

      - Must match publisher in manifest (or override it)
      - Required for command: install, query-version, share, show, unpublish, unshare, wait-for-validation.
      - Alphanumeric with hyphens, dots, underscores only

      **Example:** `mycompany` or `my-publisher-id`
    required: true
  extension-id:
    description: |-
      **Extension ID** - unique identifier within the publisher namespace.

      Available for: install, package, publish, query-version, share, show, unpublish, unshare, wait-for-installation, wait-for-validation.
      Required for: query-version, show.
      Default: none

      - Must match ID in manifest (or override it)
      - Combined with Publisher ID forms full identifier: `publisherId.extensionId`
      - Required for command: install, query-version, share, show, unpublish, unshare, wait-for-validation.
      - Alphanumeric with hyphens, dots, underscores only

      **Example:** `my-extension` or `azure-devops-tasks`
    required: true
  version-action:
    description: |-
      **Action to apply to the marketplace version**.

      Available for: query-version.
      Required for: none.
      Default: None

      - `None`: Use the current latest marketplace version
      - `Major`: Increment major and reset minor/patch
      - `Minor`: Increment minor and reset patch
      - `Patch`: Increment patch

      **Example:** If latest is `1.2.3` and action is `Minor`, result is `1.3.0`
    required: false
    default: None
  extension-version-override:
    description: |-
      **Variable name containing a version override**.

      Available for: query-version.
      Required for: none.
      Default: none

      If set and the variable exists, that value is used instead of querying marketplace.

      **Example:** `MY_VERSION` where `$``{{ env.MY_VERSION }}` is `2.1.0`
    required: false
outputs:
  proposed-version:
    description: |
      **Proposed extension version** after applying version action (query-version operation only).
    value: ${{ steps.query-version.outputs.proposed-version }}
  current-version:
    description: |
      **Current marketplace version** before applying version action (query-version operation only).
    value: ${{ steps.query-version.outputs.current-version }}
runs:
  using: composite
  steps:
    - id: query-version
      uses: jessehouwing/azdo-marketplace@main
      with:
        operation: query-version
        auth-type: ${{ inputs.auth-type }}
        token: ${{ inputs.token }}
        username: ${{ inputs.username }}
        service-url: ${{ inputs.service-url }}
        tfx-version: ${{ inputs.tfx-version }}
        publisher-id: ${{ inputs.publisher-id }}
        extension-id: ${{ inputs.extension-id }}
        version-action: ${{ inputs.version-action }}
        extension-version-override: ${{ inputs.extension-version-override }}
