name: Publish Azure DevOps Extension
description: Publish an Azure DevOps extension to the Visual Studio Marketplace
author: Jesse Houwing
branding:
  icon: upload-cloud
  color: blue
inputs:
  auth-type:
    description: |-
      Authentication type: 'pat', 'basic', or 'oidc'
      - pat: Use Personal Access Token (recommended for most users)
      - basic: Use username/password authentication (for on-premises Azure DevOps Server)
      - oidc: Use Azure OIDC via azure/login action (requires setup, see below)

      PAT Setup:
      Provide a Personal Access Token via the 'token' input

      Basic Auth Setup:
      Provide username and password via 'username' and 'password' inputs

      OIDC Setup:
      Run azure/login action BEFORE this action:

      - uses: azure/login@v2
        with:
          client-id: $``{{ secrets.AZURE_CLIENT_ID }}
          tenant-id: $``{{ secrets.AZURE_TENANT_ID }}
          subscription-id: $``{{ secrets.AZURE_SUBSCRIPTION_ID }}

      Then use auth-type: oidc (no token needed)

      See: https://jessehouwing.net/authenticate-connect-mggraph-using-oidc-in-github-actions/

      Default: pat
    required: false
    default: pat
  token:
    description: |-
      Personal Access Token for marketplace authentication
      Required when auth-type is 'pat'
      Not needed for other auth types

      Required scopes: Marketplace (Publish)
      Create a PAT at: https://dev.azure.com/_usersSettings/tokens
    required: false
  username:
    description: |-
      Username for basic authentication
      Required when auth-type is 'basic'
      Not needed for other auth types

      Use for on-premises TFS or Azure DevOps Server deployments
    required: false
  password:
    description: |-
      Password for basic authentication
      Required when auth-type is 'basic'
      Not needed for other auth types

      Use for on-premises TFS or Azure DevOps Server deployments
    required: false
  service-url:
    description: |-
      Azure DevOps service URL (optional)

      - Defaults to marketplace URL for cloud operations
      - Recommended cloud format: `https://dev.azure.com/<organization>`
      - Azure DevOps Server/TFS URLs are also supported
      - Specify custom URL for on-premises Azure DevOps Server
      - Must be HTTPS and valid Azure DevOps domain

      Examples:
      - https://marketplace.visualstudio.com (default)
      - https://dev.azure.com/myorg
      - https://myserver.com/Collection
      - https://myserver.com/tfs/Collection

      Optional for: publish, share, unshare, show, query-version, wait-for-validation
    required: false

  tfx-version:
    description: |-
      **Version of tfx-cli to use:**

      - `built-in` (default): Use tfx-cli bundled with this action
      - `path`: Use tfx-cli from system PATH
      - Version spec: Download specific version from npm (e.g., `^0.17`, `0.17.0`, `latest`)

      **Examples:** `built-in`, `path`, `^0.17`, `latest`
    required: false
    default: built-in
  publisher-id:
    description: |-
      **Publisher ID** that owns the extension.

      - Must match publisher in manifest (or override it)
      - Alphanumeric with hyphens, dots, underscores only

      **Example:** `mycompany` or `my-publisher-id`
    required: false
  extension-id:
    description: |-
      **Extension ID** - unique identifier within the publisher namespace.

      - Must match ID in manifest (or override it)
      - Combined with Publisher ID forms full identifier: `publisherId.extensionId`
      - Alphanumeric with hyphens, dots, underscores only

      **Example:** `my-extension` or `azure-devops-tasks`
    required: false
  publish-source:
    description: |-
      **Source for publish operation:**

      - `manifest` (default): Build extension from manifest and source files
      - `vsix`: Publish a pre-built .vsix package

      **Use VSIX when:** You've already packaged the extension separately
    required: false
    default: manifest
  root-folder:
    description: |-
      **Root folder** containing extension manifest and source files.

      - Defaults to repository root if not specified
      - All file paths in manifest are relative to this folder
      - Must contain `vss-extension.json` (or other manifest specified in manifest-globs)
    required: false
  manifest-globs:
    description: |-
      **Glob patterns for manifest files** (newline-separated).

      - Defaults to `vss-extension.json` if not specified
      - Can specify multiple patterns for multi-manifest scenarios
      - Patterns are relative to root-folder

      **Example:**
      ```
      vss-extension.json
      manifests/**/*.json
      ```
    required: false
  vsix-file:
    description: |-
      **Path to pre-built .vsix file** (for publish operation).

      - Use when publish-source is 'vsix'
      - File must be a valid extension package
      - Supports GitHub Actions expressions

      **Example:** `$``{{ github.workspace }}/dist/my-extension.vsix`
    required: false
  extension-version:
    description: |-
      **Override extension version** specified in manifest.

      - Must follow semantic versioning: `major.minor.patch`
      - Useful for CI/CD pipelines to inject build numbers

      **Examples:** `1.2.3`, `1.0.$``{{ github.run_number }}`
    required: false
  extension-name:
    description: |-
      **Override extension display name** shown in marketplace.

      - Does not affect the extension ID
      - Useful for creating branded variants (e.g., "My Extension (Dev)")

      **Example:** `My Extension - Development`
    required: false
  extension-visibility:
    description: |-
      **Override extension visibility** in marketplace.

      - `private`: Only visible to organizations you share it with
      - `public`: Visible to everyone in the marketplace
      - `private_preview`: Private extension in preview mode
      - `public_preview`: Public extension in preview mode

      **Note:** Private extensions must be explicitly shared with organizations
    required: false
  share-with:
    description: |-
      **Organizations to share extension with** (newline-separated).

      - Format: organization name OR URL
      - Supported URLs: `https://dev.azure.com/ORG`, `https://ORG.visualstudio.com`
      - URL inputs are normalized to organization name automatically

      **Example:**
      ```
      myorg1
      myorg2
      contoso
      ```
    required: false
  no-wait-validation:
    description: |-
      **Do not wait for marketplace validation** after publishing.

      - By default, action waits for validation (can take several minutes)
      - Enable to publish and continue immediately
      - Extension may not be immediately available

      **Default:** `false` (waits for validation)
    required: false
    default: 'false'
  update-tasks-version:
    description: |-
      **Automatically update task versions** to match extension version.

      - Updates all task.json files in the extension
      - Useful for keeping task and extension versions in sync

      **Default:** `false`
    required: false
    default: 'false'
  update-tasks-id:
    description: |-
      **Generate new deterministic task IDs** for all tasks.

      - Creates UUID v5 IDs based on publisher + extension + task name
      - Use when creating extension variants (dev, test versions)

      **Warning:** Changing task IDs creates new tasks - existing pipelines won't auto-update

      **Default:** `false`
    required: false
    default: 'false'
outputs:
  vsix-path:
    description: |-
      **Path to generated .vsix file** (package operation only).

      **Example usage:**
      ```yaml
      - uses: jessehouwing/azure-devops-extension-tasks@refactor/v6
        id: package
        with:
          operation: package

      - run: echo "VSIX at $``{{ steps.package.outputs.vsix-path }}"
      ```
    value: ${{ steps.publish.outputs.vsix-path }}
runs:
  using: composite
  steps:
    - id: publish
      uses: jessehouwing/azure-devops-extension-tasks@refactor/v6
      with:
        operation: publish
        auth-type: ${{ inputs.auth-type }}
        token: ${{ inputs.token }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        service-url: ${{ inputs.service-url }}
        tfx-version: ${{ inputs.tfx-version }}
        publisher-id: ${{ inputs.publisher-id }}
        extension-id: ${{ inputs.extension-id }}
        publish-source: ${{ inputs.publish-source }}
        root-folder: ${{ inputs.root-folder }}
        manifest-globs: ${{ inputs.manifest-globs }}
        vsix-file: ${{ inputs.vsix-file }}
        extension-version: ${{ inputs.extension-version }}
        extension-name: ${{ inputs.extension-name }}
        extension-visibility: ${{ inputs.extension-visibility }}
        share-with: ${{ inputs.share-with }}
        no-wait-validation: ${{ inputs.no-wait-validation }}
        update-tasks-version: ${{ inputs.update-tasks-version }}
        update-tasks-id: ${{ inputs.update-tasks-id }}
