name: Package Azure DevOps Extension
description: Create a .vsix package for an Azure DevOps extension
author: Jesse Houwing
branding:
  icon: package
  color: blue
inputs:
  tfx-version:
    description: |-
      **Version of tfx-cli to use:**

      Available for: install, package, publish, query-version, share, show, unpublish, unshare, wait-for-installation, wait-for-validation.
      Required for: none.
      Default: built-in

      - `built-in` (default): Use bundled tfx-cli JS entrypoint
      - `path`: Use tfx-cli from system PATH (provided by your environment)
      - Version spec: Download specific version from npm (e.g., `^0.17`, `0.17.0`, `latest`)

      **Examples:** `built-in`, `path`, `^0.17`, `latest`
    required: false
    default: built-in
  publisher-id:
    description: |-
      **Publisher ID** that owns the extension.

      Available for: install, package, publish, query-version, share, show, unpublish, unshare, wait-for-installation, wait-for-validation.
      Required for: query-version, show.
      Default: none

      - Must match publisher in manifest (or override it)
      - Required for command: install, query-version, share, show, unpublish, unshare, wait-for-validation.
      - Alphanumeric with hyphens, dots, underscores only

      **Example:** `mycompany` or `my-publisher-id`
    required: false
  extension-id:
    description: |-
      **Extension ID** - unique identifier within the publisher namespace.

      Available for: install, package, publish, query-version, share, show, unpublish, unshare, wait-for-installation, wait-for-validation.
      Required for: query-version, show.
      Default: none

      - Must match ID in manifest (or override it)
      - Combined with Publisher ID forms full identifier: `publisherId.extensionId`
      - Required for command: install, query-version, share, show, unpublish, unshare, wait-for-validation.
      - Alphanumeric with hyphens, dots, underscores only

      **Example:** `my-extension` or `azure-devops-tasks`
    required: false
  manifest-file:
    description: |-
      **Manifest file path(s)** (newline-separated).

      Available for: package, publish, wait-for-installation.
      Required for: none.
      Default: none

      - Defaults to `vss-extension.json` if not specified
      - Can specify multiple manifest files
      - Patterns are relative to the current working directory

      **Example:**
      ```
      vss-extension.json
      manifests/dev/vss-extension.json
      manifests/prod/vss-extension.json
      ```
    required: false
  manifest-file-js:
    description: |-
      **Manifest JS file path** for tfx `--manifest-js`.

      Available for: package, publish.
      Required for: none.
      Default: none

      - Path to JavaScript file exporting a function that returns manifest JSON
      - Path is relative to the current working directory
      - Optional alternative/addition to `manifest-file`
    required: false
  overrides-file:
    description: |-
      **Overrides JSON file path** for tfx `--overrides-file`.

      Available for: package, publish.
      Required for: none.
      Default: none

      - Existing JSON is preserved unless overridden by explicit inputs
      - Manifest updates from this action are merged into this file
      - Path is relative to the current working directory
    required: false
  extension-version:
    description: |-
      **Override extension version** specified in manifest.

      Available for: package, publish, wait-for-validation.
      Required for: none.
      Default: none

      - Must follow semantic versioning: `major.minor.patch`
      - Useful for CI/CD pipelines to inject build numbers

      **Examples:** `1.2.3`, `1.0.$``{{ github.run_number }}`
    required: false
  extension-name:
    description: |-
      **Override extension display name** shown in marketplace.

      Available for: package, publish.
      Required for: none.
      Default: none

      - Does not affect the extension ID
      - Useful for creating branded variants (e.g., "My Extension (Dev)")

      **Example:** `My Extension - Development`
    required: false
  extension-visibility:
    description: |-
      **Override extension visibility** in marketplace.

      Available for: package, publish.
      Required for: none.
      Default: none

      - `private`: Only visible to organizations you share it with
      - `public`: Visible to everyone in the marketplace
      - `private_preview`: Private extension in preview mode
      - `public_preview`: Public extension in preview mode

      **Note:** Private extensions must be explicitly shared with organizations
    required: false
  localization-root:
    description: |-
      **Folder containing localization files** for multi-language support.

      Available for: package, publish.
      Required for: none.
      Default: none

      - Should contain language-specific resource files
      - Typical structure: `localization/{locale}/resources.resjson`
      - If not specified, no localization is included

      **Example:** `$``{{ github.workspace }}/localization`
    required: false
  extension-pricing:
    description: |-
      **Override extension pricing model**.

      Available for: package, publish.
      Required for: none.
      Default: default

      - `default`: Use pricing from manifest
      - `free`: Extension is free to use
      - `paid`: Extension requires payment

      **Note:** Paid extensions require additional marketplace publisher verification
    required: false
    default: default
  output-path:
    description: |-
      **Output directory** for generated/final .vsix file.

      Available for: package, publish.
      Required for: none.
      Default: none

      - Defaults to current directory if not specified
      - Directory will be created if it doesn't exist
      - Actual filename is based on publisher.extensionId-version.vsix

      **Output:** Full path stored in `vsix-path` output
    required: false
  bypass-validation:
    description: |-
      **Skip extension validation checks** during package/publish.

      Available for: package.
      Required for: none.
      Default: false

      - Not recommended for production use
      - Use only when validation incorrectly fails
      - May result in extension rejection by marketplace

      **Default:** `false` (validation enabled)
    required: false
    default: 'false'
  update-tasks-version:
    description: |-
      **How to update task versions** to match extension version.

      Available for: package, publish.
      Required for: none.
      Default: none

      - `none`: Do not update task versions
      - `major`: Replace major, minor, patch
      - `minor`: Replace minor, patch
      - `patch`: Replace patch only

      **Default:** `none`
    required: false
    default: none
  update-tasks-id:
    description: |-
      **Generate new deterministic task IDs** for all tasks.

      Available for: package, publish.
      Required for: none.
      Default: false

      - Creates UUID v5 IDs based on publisher + extension + task name
      - Use when creating extension variants (dev, test versions)

      **Warning:** Changing task IDs creates new tasks - existing pipelines won't auto-update

      **Default:** `false`
    required: false
    default: 'false'
outputs:
  vsix-path:
    description: |
      **Path to generated .vsix file** (package operation only).

      **Example usage:**
      ```yaml
      - uses: jessehouwing/azdo-marketplace@v6
        id: package
        with:
          operation: package

      - run: echo "VSIX at $``{{ steps.package.outputs.vsix-path }}"
      ```
    value: ${{ steps.package.outputs.vsix-path }}
runs:
  using: composite
  steps:
    - id: package
      uses: jessehouwing/azdo-marketplace@main
      with:
        operation: package
        tfx-version: ${{ inputs.tfx-version }}
        publisher-id: ${{ inputs.publisher-id }}
        extension-id: ${{ inputs.extension-id }}
        manifest-file: ${{ inputs.manifest-file }}
        manifest-file-js: ${{ inputs.manifest-file-js }}
        overrides-file: ${{ inputs.overrides-file }}
        extension-version: ${{ inputs.extension-version }}
        extension-name: ${{ inputs.extension-name }}
        extension-visibility: ${{ inputs.extension-visibility }}
        localization-root: ${{ inputs.localization-root }}
        extension-pricing: ${{ inputs.extension-pricing }}
        output-path: ${{ inputs.output-path }}
        bypass-validation: ${{ inputs.bypass-validation }}
        update-tasks-version: ${{ inputs.update-tasks-version }}
        update-tasks-id: ${{ inputs.update-tasks-id }}
