name: Package Azure DevOps Extension
description: Create a .vsix package for an Azure DevOps extension
author: Jesse Houwing
branding:
  icon: package
  color: blue
inputs:
  tfx-version:
    description: |-
      **Version of tfx-cli to use:**

      - `built-in` (default): Use tfx-cli bundled with this action
      - `path`: Use tfx-cli from system PATH
      - Version spec: Download specific version from npm (e.g., `^0.17`, `0.17.0`, `latest`)

      **Examples:** `built-in`, `path`, `^0.17`, `latest`
    required: false
    default: built-in
  publisher-id:
    description: |-
      **Publisher ID** that owns the extension.

      - Must match publisher in manifest (or override it)
      - Alphanumeric with hyphens, dots, underscores only

      **Example:** `mycompany` or `my-publisher-id`
    required: false
  extension-id:
    description: |-
      **Extension ID** - unique identifier within the publisher namespace.

      - Must match ID in manifest (or override it)
      - Combined with Publisher ID forms full identifier: `publisherId.extensionId`
      - Alphanumeric with hyphens, dots, underscores only

      **Example:** `my-extension` or `azure-devops-tasks`
    required: false
  root-folder:
    description: |-
      **Root folder** containing extension manifest and source files.

      - Defaults to repository root if not specified
      - All file paths in manifest are relative to this folder
      - Must contain `vss-extension.json` (or other manifest specified in manifest-globs)
    required: false
  manifest-globs:
    description: |-
      **Glob patterns for manifest files** (newline-separated).

      - Defaults to `vss-extension.json` if not specified
      - Can specify multiple patterns for multi-manifest scenarios
      - Patterns are relative to root-folder

      **Example:**
      ```
      vss-extension.json
      manifests/**/*.json
      ```
    required: false
  extension-version:
    description: |-
      **Override extension version** specified in manifest.

      - Must follow semantic versioning: `major.minor.patch`
      - Useful for CI/CD pipelines to inject build numbers

      **Examples:** `1.2.3`, `1.0.${{ github.run_number }}`
    required: false
  extension-name:
    description: |-
      **Override extension display name** shown in marketplace.

      - Does not affect the extension ID
      - Useful for creating branded variants (e.g., "My Extension (Dev)")

      **Example:** `My Extension - Development`
    required: false
  extension-visibility:
    description: |-
      **Override extension visibility** in marketplace.

      - `private`: Only visible to organizations you share it with
      - `public`: Visible to everyone in the marketplace
      - `private_preview`: Private extension in preview mode
      - `public_preview`: Public extension in preview mode

      **Note:** Private extensions must be explicitly shared with organizations
    required: false
  output-path:
    description: |-
      **Output directory** for generated .vsix file (package operation).

      - Defaults to current directory if not specified
      - Directory will be created if it doesn't exist
      - Actual filename is based on publisher.extensionId-version.vsix

      **Output:** Full path stored in `vsix-path` output
    required: false
  output-variable:
    description: |-
      **Name to use for storing output** (deprecated - use outputs instead).

      **Package:** Stores path to generated .vsix file
      **Show:** Stores JSON metadata about the extension

      **Note:** Prefer using action outputs (`steps.<id>.outputs.vsix-path`)
    required: false
  bypass-validation:
    description: |-
      **Skip extension validation checks** during package/publish.

      - Not recommended for production use
      - Use only when validation incorrectly fails
      - May result in extension rejection by marketplace

      **Default:** `false` (validation enabled)
    required: false
    default: 'false'
  rev-version:
    description: |-
      **Automatically increment the patch version** of the extension.

      - Increments the last digit: `1.2.3` → `1.2.4`
      - Applied before packaging
      - Does not modify source manifest file

      **Default:** `false`
    required: false
    default: 'false'
  update-tasks-version:
    description: |-
      **Automatically update task versions** to match extension version.

      - Updates all task.json files in the extension
      - Useful for keeping task and extension versions in sync

      **Default:** `false`
    required: false
    default: 'false'
  update-tasks-id:
    description: |-
      **Generate new deterministic task IDs** for all tasks.

      - Creates UUID v5 IDs based on publisher + extension + task name
      - Use when creating extension variants (dev, test versions)

      **Warning:** Changing task IDs creates new tasks - existing pipelines won't auto-update

      **Default:** `false`
    required: false
    default: 'false'
outputs:
  vsix-path:
    description: |-
      **Path to generated .vsix file** (package operation only).

      **Example usage:**
      ```yaml
      - uses: jessehouwing/azure-devops-extension-tasks@v6
        id: package
        with:
          operation: package

      - run: echo "VSIX at ${{ steps.package.outputs.vsix-path }}"
      ```
    value: ${{ steps.package.outputs.vsix-path }}
runs:
  using: composite
  steps:
    - id: package
      uses: jessehouwing/azure-devops-extension-tasks@v6
      with:
        operation: package
        tfx-version: ${{ inputs.tfx-version }}
        publisher-id: ${{ inputs.publisher-id }}
        extension-id: ${{ inputs.extension-id }}
        root-folder: ${{ inputs.root-folder }}
        manifest-globs: ${{ inputs.manifest-globs }}
        extension-version: ${{ inputs.extension-version }}
        extension-name: ${{ inputs.extension-name }}
        extension-visibility: ${{ inputs.extension-visibility }}
        output-path: ${{ inputs.output-path }}
        output-variable: ${{ inputs.output-variable }}
        bypass-validation: ${{ inputs.bypass-validation }}
        rev-version: ${{ inputs.rev-version }}
        update-tasks-version: ${{ inputs.update-tasks-version }}
        update-tasks-id: ${{ inputs.update-tasks-id }}
